disabled_rules:
  - identifier_name

line_length: 
  warning: 300
  error: 300
  ignores_comments: true
  ignores_urls: true

#Setting threshold for warning
warning_threshold: 10


cyclomatic_complexity:
  warning: 15
  error: 10

excluded:
- Pods

